// client/src/pages/import/index.vue
<template>
  <view class="page">
    <!-- ① 选择音视频文件 -->
    <view class="step">
      <text class="step-title">① 选择音视频文件 *</text>
      <view v-if="!mediaFile" class="picker-box" @click="chooseMedia">
        <text class="picker-icon">📁</text>
        <text class="picker-text">点击选择</text>
        <text class="picker-hint">支持 mp3 wav m4a mp4 mov 等</text>
      </view>
      <view v-else class="file-info">
        <text class="file-name">✓ {{ mediaFile.name }}</text>
        <text class="file-meta">{{ mediaTypeText }} · {{ formatBytes(mediaFile.size) }}</text>
        <text v-if="mediaFromTts" class="tts-badge">由文字转语音生成</text>
      </view>
    </view>

    <!-- ② 选择字幕文件 -->
    <view class="step">
      <text class="step-title">② 选择字幕文件 *</text>
      <view v-if="!subtitleFile" class="picker-box" @click="chooseSubtitle">
        <text class="picker-icon">📄</text>
        <text class="picker-text">点击选择</text>
        <text class="picker-hint">支持 .srt / .lrc</text>
      </view>
      <view v-else class="file-info">
        <text class="file-name">✓ {{ subtitleFile.name }}</text>
        <text v-if="parseSummary" class="file-ok">
          {{ parseSummary.format.toUpperCase() }} ·
          {{ parseSummary.isBilingual ? '双语字幕' : '单语字幕' }} ·
          {{ parseSummary.sentenceCount }} 句 · {{ formatMs(parseSummary.totalDurationMs) }}
          ✓解析成功
        </text>
        <text v-if="parseError" class="file-error">{{ parseError }}</text>
      </view>
      <!-- 字幕与媒体时长偏差警告（>5s 不阻断，原型设计 §3.1） -->
      <view v-if="durationMismatch" class="warning-bar">
        <text>⚠ 字幕末句 {{ formatMs(subtitleEndMs) }} 与媒体时长 {{ formatMs(mediaDurationMs) }} 略有偏差</text>
      </view>
    </view>

    <!-- ③ 材料名称 -->
    <view class="step">
      <text class="step-title">③ 材料名称</text>
      <input v-model="materialName" class="name-input" maxlength="50" placeholder="默认取文件名" />
    </view>

    <button class="btn-submit" :disabled="!canSubmit" @click="submit">完成导入</button>
  </view>
</template>

<script setup lang="ts">
import { computed, ref } from 'vue';
import { onLoad } from '@dcloudio/uni-app';
import { useMaterialStore } from '@/stores/material';
import { parseSubtitle, SubtitleParseError } from '@/core/subtitle';
import { formatBytes, formatMs } from '@/utils/format';
import { baseNameOf, isMediaFile, isSubtitleFile, mediaTypeOf } from '@/utils/file';
import { getStorage } from '@/platform/storage';

interface PickedFile {
  name: string;
  size: number;
  /** H5 Blob；小程序临时文件路径 */
  data: Blob | string;
}

const materialStore = useMaterialStore();

const mediaFile = ref<PickedFile | null>(null);
const subtitleFile = ref<PickedFile | null>(null);
const subtitleText = ref<string | null>(null);
const materialName = ref('');
const parseError = ref('');
const mediaFromTts = ref(false);
const submitting = ref(false);

interface ParseSummary {
  format: string;
  isBilingual: boolean;
  sentenceCount: number;
  totalDurationMs: number;
}
const parseSummary = ref<ParseSummary | null>(null);

const mediaDurationMs = ref(0);

/** TTS 一键带入（?source=tts&taskId=）：自动填充音频与字幕（原型设计 §4.2） */
onLoad(async (query) => {
  if (query?.source === 'tts' && query.taskId) {
    const task = materialStore.getTtsTask(query.taskId);
    if (task) {
      mediaFromTts.value = true;
      const storage = getStorage();
      // #ifdef H5
      const src = await storage.resolveFileSrc(task.audioRef);
      const blob = await fetch(src).then((r) => r.blob());
      mediaFile.value = { name: `tts-${task.voice}.wav`, size: blob.size, data: blob };
      // #endif
      // #ifdef MP-WEIXIN
      mediaFile.value = {
        name: `tts-${task.voice}.wav`,
        size: 0,
        data: task.audioRef
      };
      // #endif
      mediaDurationMs.value = task.durationMs;
      if (task.srt) {
        subtitleText.value = task.srt;
        subtitleFile.value = { name: `tts-${task.voice}.srt`, size: task.srt.length, data: '' };
        runParse(task.srt);
      }
      materialName.value = `TTS ${new Date(task.createdAt).toLocaleDateString()}`;
    }
  }
});

const mediaTypeText = computed(() =>
  mediaFile.value ? (mediaTypeOf(mediaFile.value.name) === 'video' ? '视频' : '音频') : ''
);

const canSubmit = computed(
  () => mediaFile.value != null && parseSummary.value != null && !submitting.value
);

/** 字幕末句与媒体时长偏差 >5s（原型设计 §3.1） */
const subtitleEndMs = computed(() => parseSummary.value?.totalDurationMs ?? 0);
const durationMismatch = computed(
  () =>
    parseSummary.value != null &&
    mediaDurationMs.value > 0 &&
    Math.abs(subtitleEndMs.value - mediaDurationMs.value) > 5000
);

function chooseMedia(): void {
  // #ifdef H5
  const input = document.createElement('input');
  input.type = 'file';
  input.accept = 'audio/*,video/*,.mp3,.wav,.m4a,.mp4,.mov';
  input.onchange = () => {
    const f = input.files?.[0];
    if (!f) return;
    if (!isMediaFile(f.name)) {
      uni.showToast({ title: '该格式可能无法播放', icon: 'none' });
    }
    mediaFile.value = { name: f.name, size: f.size, data: f };
    materialName.value = materialName.value || baseNameOf(f.name);
    probeMediaDuration(f);
  };
  input.click();
  // #endif
  // #ifdef MP-WEIXIN
  uni.chooseMessageFile({
    count: 1,
    type: 'file',
    extension: ['mp3', 'wav', 'm4a', 'mp4', 'mov'],
    success: (res) => {
      const f = res.tempFiles[0];
      mediaFile.value = { name: f.name, size: f.size, data: f.path };
      materialName.value = materialName.value || baseNameOf(f.name);
    }
  });
  // #endif
}

function chooseSubtitle(): void {
  // #ifdef H5
  const input = document.createElement('input');
  input.type = 'file';
  input.accept = '.srt,.lrc';
  input.onchange = async () => {
    const f = input.files?.[0];
    if (!f) return;
    if (!isSubtitleFile(f.name)) {
      parseError.value = '仅支持 .srt / .lrc 字幕文件';
      return;
    }
    const text = await f.text();
    subtitleFile.value = { name: f.name, size: f.size, data: f };
    subtitleText.value = text;
    runParse(text);
  };
  input.click();
  // #endif
  // #ifdef MP-WEIXIN
  uni.chooseMessageFile({
    count: 1,
    type: 'file',
    extension: ['srt', 'lrc'],
    success: async (res) => {
      const f = res.tempFiles[0];
      subtitleFile.value = { name: f.name, size: f.size, data: f.path };
      try {
        const fs = uni.getFileSystemManager();
        const text = await new Promise<string>((resolve, reject) => {
          fs.readFile({
            filePath: f.path,
            encoding: 'utf8',
            success: (r) => resolve(String(r.data)),
            fail: (e) => reject(new Error(e.errMsg))
          });
        });
        subtitleText.value = text;
        runParse(text);
      } catch (e) {
        parseError.value = e instanceof Error ? e.message : '字幕读取失败';
      }
    }
  });
  // #endif
}

/** 选择字幕文件后即时解析（纯前端自研解析器，零网络请求） */
function runParse(text: string): void {
  parseError.value = '';
  parseSummary.value = null;
  try {
    const data = parseSubtitle(text, undefined, subtitleFile.value?.name);
    parseSummary.value = {
      format: data.format,
      isBilingual: data.isBilingual,
      sentenceCount: data.sentences.length,
      totalDurationMs: data.totalDurationMs
    };
  } catch (e) {
    parseError.value =
      e instanceof SubtitleParseError ? e.message : '字幕解析失败，请检查文件内容';
  }
}

/** H5：用临时 video/audio 元素探测媒体时长 */
function probeMediaDuration(file: Blob): void {
  // #ifdef H5
  const url = URL.createObjectURL(file);
  const el = document.createElement(mediaTypeOf(mediaFile.value!.name) === 'video' ? 'video' : 'audio');
  el.preload = 'metadata';
  el.onloadedmetadata = () => {
    mediaDurationMs.value = el.duration * 1000;
    URL.revokeObjectURL(url);
  };
  el.src = url;
  // #endif
}

async function submit(): Promise<void> {
  if (!canSubmit.value || !mediaFile.value) return;
  submitting.value = true;
  try {
    const material = await materialStore.importMaterial({
      mediaFile: mediaFile.value.data,
      mediaFileName: mediaFile.value.name,
      mediaSizeBytes: mediaFile.value.size,
      subtitleText: subtitleText.value,
      subtitleFileName: subtitleFile.value?.name,
      name: materialName.value
    });
    // 完成导入 → 自动进入 P2 播放器（原型设计 §3.1）
    uni.redirectTo({ url: `/pages/player/index?materialId=${material.id}` });
  } catch (e) {
    uni.showToast({
      title: e instanceof Error ? e.message : '导入失败',
      icon: 'none'
    });
  } finally {
    submitting.value = false;
  }
}
</script>

<style lang="scss" scoped>
.page {
  padding: 24rpx;
  max-width: 960rpx;
  margin: 0 auto;
}
.step {
  margin-bottom: 32rpx;
}
.step-title {
  font-size: 28rpx;
  font-weight: 600;
  display: block;
  margin-bottom: 16rpx;
}
.picker-box {
  border: 2rpx dashed #c0c4cc;
  border-radius: 20rpx;
  padding: 48rpx;
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 8rpx;
}
.picker-icon {
  font-size: 64rpx;
}
.picker-text {
  font-size: 28rpx;
  color: #1f2329;
}
.picker-hint {
  font-size: 22rpx;
  color: #8a9199;
}
.file-info {
  background: #fff;
  border-radius: 20rpx;
  padding: 24rpx;
  display: flex;
  flex-direction: column;
  gap: 8rpx;
}
.file-name {
  font-size: 28rpx;
}
.file-meta {
  font-size: 22rpx;
  color: #646a73;
}
.tts-badge {
  font-size: 20rpx;
  color: #3b6ef0;
  background: #eef2ff;
  border-radius: 8rpx;
  padding: 4rpx 12rpx;
  align-self: flex-start;
}
.file-ok {
  font-size: 22rpx;
  color: #2ea44f;
}
.file-error {
  font-size: 22rpx;
  color: #d83931;
}
.warning-bar {
  margin-top: 16rpx;
  background: #fff7e6;
  border-radius: 12rpx;
  padding: 16rpx 24rpx;
  font-size: 22rpx;
  color: #e8890c;
}
.name-input {
  background: #fff;
  border-radius: 12rpx;
  padding: 20rpx 24rpx;
  font-size: 28rpx;
}
.btn-submit {
  background: #3b6ef0;
  color: #fff;
  border-radius: 12rpx;
  font-size: 30rpx;
  &[disabled] {
    background: #c0c4cc;
  }
}
</style>

// client/components/pages/import.tsx
import { useEffect, useState } from 'react'
import { Navigate, useSearchParams } from 'react-router-dom'
import { AlertTriangle, Check } from 'lucide-react'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Shell, PageIntro } from '@/components/shared/shell'
import { formatDuration } from '@/components/shared/player-parts'
import { parseSubtitle, SubtitleParseError } from '@/core/subtitle'
import type { SubtitleData } from '@/types/subtitle'
import { putMaterialRecord, putMediaBlob, deleteMediaBlob } from '@/stores/material-store'
import type { MaterialRecord } from '@/platform/storage/schema'
import { estimateUsage } from '@/platform/storage/idb'
import { consumeTtsExport, readTtsExport } from '@/lib/tts-export'

/** 探测媒体真实时长（loadedmetadata；失败返回 null，不阻断导入） */
function probeMediaDuration(file: File): Promise<number | null> {
  return new Promise((resolve) => {
    if (typeof URL === 'undefined' || typeof document === 'undefined') return resolve(null)
    const url = URL.createObjectURL(file)
    const el = document.createElement(file.type.startsWith('video') ? 'video' : 'audio')
    const cleanup = () => URL.revokeObjectURL(url)
    el.preload = 'metadata'
    el.onloadedmetadata = () => { const d = Number.isFinite(el.duration) && el.duration > 0 ? Math.round(el.duration * 1000) : null; cleanup(); resolve(d) }
    el.onerror = () => { cleanup(); resolve(null) }
    el.src = url
  })
}
function formatBytes(n: number): string { return n >= 1048576 ? `${(n / 1048576).toFixed(1)} MB` : `${Math.max(1, Math.round(n / 1024))} KB` }
function baseName(fileName: string): string { return fileName.replace(/\.[^.]+$/, '').slice(0, 50) }

function ImportPage() {
  const [searchParams] = useSearchParams()
  const source = searchParams.get('source')
  const taskId = searchParams.get('taskId')
  const [name, setName] = useState('')
  const [mediaFile, setMediaFile] = useState<File | null>(null)
  const [mediaDurationMs, setMediaDurationMs] = useState<number | null>(null)
  const [subtitle, setSubtitle] = useState<{ raw: string; format?: 'srt' | 'lrc'; data: SubtitleData } | null>(null)
  const [parseError, setParseError] = useState<{ message: string; line: number } | null>(null)
  const [finishError, setFinishError] = useState<string | null>(null)
  const [saving, setSaving] = useState(false)
  const [done, setDone] = useState(false)
  const [doneId, setDoneId] = useState<string | null>(null)
  const [fromTts, setFromTts] = useState(false)

  /** 即时解析字幕文本：成功渲染摘要，失败红字 + 行号（文档 P1 校验规则） */
  const applySubtitle = (text: string, format?: 'srt' | 'lrc') => {
    try {
      const data = parseSubtitle(text, format, mediaDurationMs ?? undefined)
      setSubtitle({ raw: text, format, data })
      setParseError(null)
    } catch (e) {
      setSubtitle(null)
      setParseError(e instanceof SubtitleParseError ? { message: e.message, line: e.line } : { message: '字幕解析失败', line: 0 })
    }
  }

  // 媒体时长探测完成后回填 LRC 末句 endMs（LRC 无结束时间，避免末句零时长）
  useEffect(() => {
    if (mediaDurationMs == null) return
    setSubtitle((prev) => {
      if (!prev || prev.data.format !== 'lrc') return prev
      try { return { ...prev, data: parseSubtitle(prev.raw, prev.format, mediaDurationMs) } }
      catch { return prev }
    })
  }, [mediaDurationMs])

  const handleMediaFile = async (file: File | null) => {
    if (!file) return
    setMediaFile(file)
    setName(baseName(file.name)) // 材料名默认取文件名（可编辑）
    setMediaDurationMs(await probeMediaDuration(file))
  }

  // TTS 一键带入：?source=tts&taskId= 时自动填充 ①②（产物由批次E 经 lib/tts-export 写入；缺失时空态兜底）
  useEffect(() => {
    if (source !== 'tts' || !taskId) return
    let alive = true
    readTtsExport(taskId).then(async (payload) => {
      if (!alive || !payload) return
      const { meta, audio } = payload
      const file = new File([audio], meta.audioFileName || 'tts-audio.wav', { type: audio.type || 'audio/wav' })
      setFromTts(true)
      setMediaFile(file)
      setName((meta.name || baseName(file.name)).slice(0, 50))
      setMediaDurationMs(await probeMediaDuration(file))
      applySubtitle(meta.subtitleText, meta.subtitleFormat)
    }).catch(() => { /* 空态兜底：用户可手动选择文件 */ })
    return () => { alive = false }
  }, [source, taskId])

  // 时长偏差预警：未回填的 LRC（totalDurationMs=末句起点）必然偏差巨大 → 跳过警告避免误报
  const lastStartMs = subtitle ? (subtitle.data.sentences[subtitle.data.sentences.length - 1]?.startMs ?? 0) : 0
  const lrcUnfilled = !!subtitle && subtitle.data.format === 'lrc' && subtitle.data.totalDurationMs <= lastStartMs
  const deviationMs = mediaFile && mediaDurationMs != null && subtitle && !lrcUnfilled ? Math.abs(mediaDurationMs - subtitle.data.totalDurationMs) : null
  const canFinish = !!mediaFile && !!subtitle && name.trim().length > 0 && !saving

  const finish = async () => {
    if (!canFinish || !mediaFile || !subtitle) return
    setFinishError(null)
    setSaving(true)
    const id = typeof crypto !== 'undefined' && 'randomUUID' in crypto ? crypto.randomUUID() : `m-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 10)}`
    try {
      // 写入前余量检查：quota-usage 不足文件大小×1.2 时中止；estimate 不可用（quota=0）时跳过
      const { usage, quota } = await estimateUsage()
      if (quota > 0 && usage + mediaFile.size * 1.2 > quota) {
        setFinishError('存储空间不足，请释放本地空间后重试')
        setSaving(false)
        return
      }
      await putMediaBlob(id, mediaFile) // 媒体 File → blobs store（key = materialId）
      const now = Date.now()
      const record: MaterialRecord = {
        material: {
          id, name: name.trim(),
          mediaType: mediaFile.type.startsWith('video') ? 'video' : 'audio',
          mediaRef: `idb://blobs/${id}`, mediaFileName: mediaFile.name, mediaSizeBytes: mediaFile.size,
          subtitle: { ref: `idb://materials/${id}`, format: subtitle.data.format, isBilingual: subtitle.data.isBilingual, sentenceCount: subtitle.data.sentences.length },
          durationMs: mediaDurationMs ?? subtitle.data.totalDurationMs,
          createdAt: now, lastOpenedAt: now,
        },
        subtitleData: subtitle.data, // 解析结果随元数据同存，避免重复解析（架构 §4.2）
      }
      await putMaterialRecord(record)
      if (fromTts && taskId) await consumeTtsExport(taskId)
      setDone(true)
      setDoneId(id)
    } catch {
      // 回滚已写入的 blob，避免孤儿数据
      await deleteMediaBlob(id).catch(() => {})
      setFinishError('导入失败，请重试')
      setSaving(false)
    }
  }

  if (doneId) return <Navigate to={`/player/${doneId}`} replace />

  return <Shell back><div className="mx-auto max-w-xl px-4 py-10"><PageIntro title="导入材料" eyebrow="ADD MATERIAL">{fromTts && <Badge variant="secondary">由文字转语音生成</Badge>}</PageIntro><Card><CardContent className="flex flex-col gap-6 p-6"><label className="flex flex-col gap-2 text-sm font-medium">1. 选择音视频文件<Input type="file" accept="audio/*,video/*" onChange={e => { void handleMediaFile(e.target.files?.[0] ?? null) }} /></label>{mediaFile ? <div className="rounded-xl bg-primary/10 p-4 text-sm text-primary"><Check data-icon="inline-start" />{mediaFile.name} · {mediaFile.type.startsWith('video') ? '视频' : '音频'}{mediaDurationMs != null && ` · ${formatDuration(mediaDurationMs)}`} · {formatBytes(mediaFile.size)}</div> : <div className="rounded-xl bg-muted p-4 text-sm text-muted-foreground">支持 mp3、wav、m4a、mp4、mov 等格式</div>}<label className="flex flex-col gap-2 text-sm font-medium">2. 选择字幕文件<Input type="file" accept=".srt,.lrc" onChange={e => { const f = e.target.files?.[0]; if (f) f.text().then((t) => applySubtitle(t)).catch(() => setParseError({ message: '无法读取文件内容', line: 0 })) }} /></label>{subtitle && <div className="rounded-xl bg-primary/10 p-4 text-sm text-primary"><Check data-icon="inline-start" />{subtitle.data.format.toUpperCase()} 字幕 · {subtitle.data.isBilingual ? '双语' : '仅英文'} · {subtitle.data.sentences.length} 句 · 总时长 {formatDuration(subtitle.data.totalDurationMs)} · 解析成功</div>}{parseError && <div className="rounded-xl bg-destructive/10 p-4 text-sm text-destructive">{parseError.message}{parseError.line > 0 && `，第 ${parseError.line} 行`}，请重新选择字幕文件</div>}{deviationMs != null && deviationMs > 5000 && <div className="rounded-xl border p-4 text-sm text-muted-foreground"><AlertTriangle data-icon="inline-start" />字幕与媒体时长偏差超过 5 秒，可能不匹配（不影响导入）</div>}<label className="flex flex-col gap-2 text-sm font-medium">3. 材料名称<Input value={name} onChange={e=>setName(e.target.value)} maxLength={50} placeholder="默认取文件名" /></label>{finishError && <p className="rounded-xl bg-destructive/10 p-3 text-sm text-destructive">{finishError}</p>}<Button className="w-full" onClick={finish} disabled={!canFinish}>{saving ? '导入中…' : '完成导入'}</Button>{done && <p className="text-center text-sm text-primary">导入成功，正在打开播放器…</p>}</CardContent></Card></div></Shell>
}

export { ImportPage }
